#pragma once
#include "NativeGameplayTags.h"

/*
 * WK Gameplay Tags Declaration
 *
 * - 모든 GameplayTag는 여기서 extern 선언
 * - .cpp 에서 UE_DEFINE_GAMEPLAY_TAG 와 반드시 1:1 대응
 * - 네이밍 규칙:
 *   Category.SubCategory.Detail
 *   (예: Enemy.HongHaiEr02.Ability.Attack04.01)
 */

namespace WKGameplayTags
{
	/* Player - Status */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Movement_Run);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Movement_Sprint);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Movement_Walk);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Movement_Idle);

	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_WaitForInput);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Turn);

	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Attack_Light);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Attack_Charge);

	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Dodge);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_PerfectDodge);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Invincible);

	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Jump);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_BlockInput);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Charging);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_NoStamina);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_HitReact);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Parry);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Hide);

	/*  Player - Input */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Move);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Look);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Jump);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Turn);

	
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Movement_Run);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Movement_Sprint);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Movement_Walk);

	
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Held);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Toggle);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Trigger);

	
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Held_ChargeAttack);

	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Trigger_Attack_Light);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Trigger_Dodge);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Trigger_Freeze);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Trigger_StopAndParry);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Trigger_RecoverHealth);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Trigger_Hide);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Trigger_SummonMonkey);

	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Input_Toggle_TargetLock);

	/* Player - Ability */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Death);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Charge);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Move_Turn);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dodge);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitReact);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_FreezeTarget);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_StopAndParry);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_RecoverHealth);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Hide);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SummonMonkey);

	/* Event - Ability / AnimNotify / Combat  */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Input_WaitForInput);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Input_LeftClick);

	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Player_Turn);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Player_PerfectDodge);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Player_ParrySuccess);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Player_RecoverHealth);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Player_SummonMonkey);

	/* Shared Hit Event */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Shared_Hit);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Shared_Hit_Melee);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Shared_Hit_React);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Shared_Hit_React_Shrink);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Shared_Hit_React_Light);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Shared_Hit_React_Heavy);

	/* Enemy TD Event */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_TD_SpawnRing);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_TD_SpawnProjectile);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_TD_SpawnImpact);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_TD_WeaponLeft);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_TD_WeaponRight);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_TD_WeaponBoth);

	/* Enemy HongHaiEr Event */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_HongHaiEr_SpawnThorn);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_HongHaiEr_SpawnThorn_Circle);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_HongHaiEr_SpawnThorn_Line);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_HongHaiEr_SpawnProjectile);

	/* SetByCaller */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Shared_BaseDamage);

	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Player_AttackType);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Player_AttackType_LigthAttack);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Player_AttackType_ChargeAttack);

	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Player_HitCount);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Player_HitCount_LightAttack);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Player_HitCount_ChargeAttack);

	/* Enemy - TD  */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Death);

		/* Enemy - TD - Ability */
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack03);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack04);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack05);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack06);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack07);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack08);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack10);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack12);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_Attack13);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Ability_HitReact);

		/* Enemy - TD - Cooldown */
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack03);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack04);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack05);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack06);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack07);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack08);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack10);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack12);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_TD_Cooldown_Attack13);
	

	
	/* Enemy - HongHaiEr02 */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack);

	/* Enemy - HongHaiEr02 - Ability */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_HitReact);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Death);

		/* Enemy - HongHaiEr02 - Ability - Attack*/
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack03);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack04);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack04_01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack04_02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack05);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack05_01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack05_02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack06);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack06_01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack06_02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack07_01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack07_02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack07);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack08);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack08_01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack08_02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack09);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack10);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack11);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack12);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack13);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack14);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack15);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Ability_Attack_Attack16);


		/* Enemy - HongHaiEr02 - Cooldown */
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack03);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack04);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack04_01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack04_02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack05);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack05_01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack05_02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack06);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack06_01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack06_02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack07);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack08);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack08_01);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack08_02);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack09);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack10);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack11);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack12);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack13);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack14);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack15);
		WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr02_Cooldown_Attack_Attack16);

	/* Enemy - Status */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_HitReact);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Attacking);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Invincible);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_CantNotParry);

	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr_WeaponLeft);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_HongHaiEr_WeaponRight);
	
	/* ETC */
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Clone_Ability_Attack);
	WUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Death);
}
